### ISSUE TITLE
Issues while using vault behind proxy

### ISSUE THREAD

**Issue by chetanagrawal** [ianunruh/hvac#136] opened 2017-10-06 12:03 UTC
Hi there,

We have vault running behind nginx proxy at /vault/ uri. Nginx is suppose to proxy_pass /vault/ requests to  http://localhost:8200 which works fine if we fire curl or vault cli commands. However, we are using https://github.com/TerryHowe/ansible-modules-hashivault module for vault interaction. 

So when we specify url as "https://localhost/vault" in "hashivault_init" module, then final url is constructed as  https://localhost/v1/sys/init which results in 404 error.  I would expect it to be https://localhost/**vault**/v1/sys/init

This is due to urljoin function in /usr/lib/python2.7/site-packages/hvac/v1/__init.py__

I had posted issue on https://github.com/TerryHowe/ansible-modules-hashivault/issues/33 but Terry suggested to check with you.

**Comment by chetanagrawal** [comment] 2017-10-23 05:58
@ianunruh - did you get a chance to look at this issue? Appreciate if you have any suggestion.

**Comment by otakup0pe** [comment] 2017-11-09 02:17
Hi @chetanagrawal can you provide any more details or context in order to repro? To me this _almost_ sounds like a proxy misconfiguration....

**Comment by chetanagrawal** [comment] 2017-11-10 06:03
@otakup0pe Please find the steps to reproduce this issue as below:

1. Install vault and configure it behind nginx proxy
location ~ ^/vault/(.*) {
  set $url_full         '$1';
  access_log  /var/log/nginx/vault.log upstreamlog;
  proxy_http_version     1.1;
  proxy_set_header       Cache-Control no-cache;
  proxy_hide_header      Set-Cookie;
  proxy_ignore_headers   "Set-Cookie";
  proxy_buffering        off;
  proxy_intercept_errors on;

  resolver               10.200.0.2 valid=300s;
  resolver_timeout       10s;

  proxy_pass             http://127.0.0.1:8200/$url_full;
}

2. Run the ansible playbook for Vault init
- name: VAULT | Initialize vault
  hashivault_init:
    url: "http://localhost/vault"  #Note the "vault" uri here as its behind nginx
    secret_shares: 1
    secret_threshold: 1
    verify: False

The above vault initilization fails because [urljoin function](https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L987) removes /vault from the resulting URL and final url to reach vault is constructed as "https://localhost/v1/sys/init". In this case nginx is not configured to proxy_pass /v1 requests and hence we get 404 error. Ideally I would expect the resulting URL to be "https://localhost/vault/v1/sys/init"

Let me know if this helps.

**Comment by lnomine** [comment] 2017-11-20 17:23
Hi. Same here with Kong - getkong.org. Powered by Nginx too. Can't reproduce the problem with other programs like curl.

**Comment by jeffwecan** [comment] 2018-07-20 12:45
Fixed in v0.6.1.

**Closed by jeffwecan** 2018-07-20 12:45 UTC
Labels: bug, waiting-reply
