### ISSUE TITLE
hvac.exceptions.VaultDown: no active Vault instance found

### ISSUE THREAD

**Issue by Wintermute1** [ianunruh/hvac#97] opened 2016-11-04 11:41 UTC
I keep getting this error when using the client.It sometimes returns the secret/path correctly but the majority of the time it does not. Has anyone encountered this before?

The following is the code for the client.

```
`import hvac
import os
import consul
import socket
import time
import logging

VAULT_CATALOG_NAME = "vault"
MAX_RETRIES = 10
TIME_OUT = 5

logging.basicConfig(filename='/var/tmp/vault.log', level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s', )
formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')


class VaultTokenNotFound(Exception):
    pass


class Vault(VaultTokenNotFound):
    def __init__(self, consul_host="172.x.y.z"):
        self.consul_host = consul_host
        self.token = None
        self.keys = None
        self.consul = consul.Consul(host=self.consul_host)
        self.client = self._setup_hvac()

    def _setup_hvac(self):
        vault_catalog = self.consul.catalog.service(VAULT_CATALOG_NAME)
        vault_catalog = vault_catalog[1][0]
        vault_location = 'http://{}:{}'.format(vault_catalog['Address'],
                                               vault_catalog['ServicePort'])
        try:
            self.token = os.environ.get('VAULT_USER')
        except KeyError as e:
            logging.critical("Vault token was found to be missing.")
            raise VaultTokenNotFound

        return hvac.Client(url=vault_location, token=self.token)

    def write(self, path, **kwargs):
        for ty in range(MAX_RETRIES):
            try:
                self.unseal()
                self.client.write(path, **kwargs)
                self.seal()
                break
            except socket.error as e:
                logging.info("error({0}):{1}".format(e.errno, e.strerror))
                time.sleep(TIME_OUT)
                self._setup_hvac()
                self.write(path, **kwargs)

    def read(self, path):
        self.unseal()
        content = self.client.read(path)
        self.seal()
        return content

    def delete(self, path):
        self.unseal()
        self.client.delete(path)
        self.seal()

    def unseal(self):
        if self.client.is_sealed() is True:
            try:
                self.client.unseal_multi(str(os.environ.get("VAULT_TOKENS")).split(','))
            except KeyError as e:
                logging.critical("Vault tokens missing.")
                raise VaultTokenNotFound

    def seal(self):
        if self.client.is_sealed() is False:
            self.client.seal()

    def fetch_value(self, path):
        secret_dict = self.read('secret' + path)
        return secret_dict['data']['value']
`
```

**Comment by otakup0pe** [comment] 2017-11-09 02:08
Hi @Wintermute1 are you still seeing this? If so, can you provide more information on your environment? We've seen similar things in an HA setup...

**Comment by jeffwecan** [comment] 2018-07-20 15:23
Closing this card out as its hard to pinpoint a root cause without additional details. Please reopen this issue or create a new one if required.

**Closed by jeffwecan** 2018-07-20 15:23 UTC
Labels: waiting-reply
